---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create DB for service
  mysql_db:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ gnocchi_galera_address }}"
    name: "{{ gnocchi_galera_database }}"
    state: "present"
  delegate_to: "{{ gnocchi_db_setup_host }}"
  no_log: True

- name: Grant access to the DB for the service
  mysql_user:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ gnocchi_galera_address }}"
    name: "{{ gnocchi_galera_user }}"
    password: "{{ gnocchi_container_mysql_password }}"
    host: "{{ item }}"
    state: "present"
    priv: "{{ gnocchi_galera_database }}.*:ALL"
  delegate_to: "{{ gnocchi_db_setup_host }}"
  with_items:
    - "localhost"
    - "%"
  no_log: True

- name: Perform a Gnocchi DB sync
  command: "{{ gnocchi_bin }}/gnocchi-upgrade {{ gnocchi_db_sync_options }}"
  become: yes
  become_user: "{{ gnocchi_system_user_name }}"
  changed_when: false
